import { PACKAGES, ADDONS, REVEAL, priceCaption } from './content.mjs';

const nube = PACKAGES.find(p => p.id === 'basico');
const estrella = PACKAGES.find(p => p.id === 'estrella');
const sueno = PACKAGES.find(p => p.id === 'premium');
const torta = ADDONS.find(a => a.id === 'torta');
const kit = REVEAL.packages.find(p => p.id === 'kit');
const section = (heading, ...paragraphs) => ({ heading, paragraphs });

export const IDEAS = [
 {
  slug: 'ideas-para-baby-shower', title: 'Ideas para baby shower en Paraguay',
  h1: 'Ideas para baby shower en Paraguay: temáticas, juegos y cuánto cuesta',
  description: 'Organizá tu baby shower con ideas de temáticas, invitados, bocaditos y presupuesto. Compará estimaciones y prepará una consulta con los datos clave.',
  datePublished: '2026-09-19', theme: 'nubes-y-ositos', offer: estrella,
  cta: 'Si querés que lo hagamos nosotros', image: 'Composición ilustrativa de una mesa con nubes, ositos y globos en tonos suaves',
  intro: 'Un baby shower puede ser una merienda íntima o una reunión con toda la familia. Antes de elegir globos, pensá qué querés compartir y cuánto trabajo podés asumir. En Asunción y Gran Asunción, el espacio disponible, el calor y la posibilidad de pasar bajo techo pesan tanto como la decoración. Esta guía te ayuda a ordenar decisiones sin comprar cosas que después no vas a usar.',
  sections: [
   section('Temáticas para elegir',
    'Elegí una idea central y dos o tres colores. Nubes y ositos funciona con crema, celeste suave y verde salvia; safari permite combinar hojas y animales; mariposas se puede resolver con figuras de papel y una paleta clara. No hace falta que cada plato tenga un dibujo. Repetir los mismos tonos en cartel, mantel y servilletas da unidad sin llenar todos los rincones.',
    'Armá una pequeña selección de referencias y anotá qué te gusta de cada una: el arco, la altura de la mesa o el cartel. Una imagen sirve para conversar sobre el resultado, pero no confirma materiales ni medidas. Si celebrás en una sala chica, priorizá un solo fondo para fotos. Dejá la decoración de las mesas en segundo plano para que haya lugar para apoyar vasos y platos.'),
   section('Cuántos invitados y dónde',
    'Escribí una lista con adultos y niños antes de elegir el lugar. Contá también a quienes ayudan durante la reunión. Mandá una invitación con fecha, horario, ubicación y un pedido claro de confirmación. Un número aproximado sirve para empezar; las respuestas después permiten ajustar comida y sillas. No calcules el espacio solo por la cantidad de personas que entran de pie.',
    'Recorré la casa como si fueras una invitada: entrada, baño, mesa de comida y asiento. Evitá que la fila de bocaditos corte el paso. Si pensás usar patio o quincho, definí dónde seguiría la reunión si llueve. Consultá las reglas del salón o edificio, especialmente ingreso de materiales, uso de paredes y horario de salida. Una foto amplia y medidas del rincón elegido ayudan a explicar el espacio.'),
   section('Menú de bocaditos típico (chipitas, empanaditas, alfajores)',
    'Para una merienda podés combinar chipitas, empanaditas y alfajores con otras opciones dulces y saladas. Elegí por variedad y facilidad para servir, no solo por cómo se ve la mesa. Preguntá qué sabores prefiere la familia y si alguien necesita una alternativa particular. Confirmá con quien prepara la comida qué puede ofrecer y cómo identificar cada bandeja; no des por hecha ninguna adaptación.',
    'Separá el cálculo de comida del de bebidas, hielo, vasos y servilletas. Anotá quién recibe las bandejas y quién repone la mesa para que esa tarea no quede sin dueño. Si una tía lleva una preparación, registrala junto a lo encargado. Así evitás duplicar postres y descubrir a último momento que falta algo salado. Confirmá el momento de entrega y seguí las indicaciones de conservación de cada proveedor.'),
   section('Presupuesto real (rangos de los combos)',
    `Compará el alcance antes de comparar números. ${nube.name}: ${priceCaption(nube.price)} Es una propuesta de decoración; no equivale a una merienda completa. ${estrella.name}: ${priceCaption(estrella.price)} Sumá a la comparación los invitados incluidos, las unidades de bocaditos y los elementos de mesa para entender qué resolvés con cada alternativa.`,
    `${sueno.name}: ${priceCaption(sueno.price)} La torta y los souvenirs están contemplados en esta estimación. Como adicional para otra propuesta, ${torta.name}: ${priceCaption(torta.price)} Revisá primero lo incluido para no sumar dos veces el mismo concepto. Separá también salón, mesas, sillas, mantelería y limpieza posterior: no están incluidos en los combos. Pedí una propuesta escrita con zona, cantidades y alcance. Un monto inicial orienta la conversación; no confirma disponibilidad ni constituye un acuerdo.`),
   section('Cuándo hacerlo (semana 30 a 34)',
    'Si estás pensando en las semanas 30 a 34 como ventana para el encuentro, tomalas como una referencia de organización, no como una indicación médica. Elegí la fecha según tu comodidad, tus preferencias y la orientación de tu profesional de salud cuando corresponda. También podés hacer una reunión más temprana o posterior: el festejo no necesita ajustarse a una semana para tener sentido.',
    'Con la fecha tentativa, repartí tareas concretas: invitaciones, comida, juegos y preparación del espacio. Consultá con unas tres semanas de anticipación si querés apoyo con decoración, dejando margen para conversar alternativas. Prepará un programa sencillo con bienvenida, merienda, dos juegos y fotos, sin obligar a nadie a participar. Designá una persona para recibir consultas ese día. La mejor organización es la que te permite sentarte, conversar y disfrutar sin revisar una lista a cada rato.')
  ]
 },
 {
  slug: 'juegos-para-baby-shower', title: '10 juegos para baby shower | Guía práctica',
  h1: '10 juegos para baby shower',
  description: 'Elegí juegos de baby shower con materiales fáciles de conseguir, reglas claras y opciones para participar sentado. Prepará una tarde sin complicaciones.',
  datePublished: '2026-09-19', theme: 'safari', offer: estrella,
  cta: 'Los combos Estrella y Sueño incluyen los juegos impresos', image: 'Composición ilustrativa de tarjetas, lápices y una mesa de juegos en tonos salvia',
  intro: 'Los juegos sirven para que la familia converse, no para llenar cada minuto. Elegí dos o tres según el grupo y guardá otro por si queda tiempo. Prepará lápices, tarjetas y una explicación breve antes de empezar. En una reunión con distintas edades, alterná actividades tranquilas y por equipos. Participar tiene que ser opcional: mirar y alentar también es una forma de compartir.',
  sections: [
   section('1. Bingo del bebé', 'Dibujá una cuadrícula y escribí objetos como pañal, manta, sonajero o babero en posiciones distintas. Prepará papelitos con las mismas palabras y sacalos de una bolsa. Cada persona marca lo que escucha; gana quien completa la línea acordada. Mostrá un ejemplo antes de repartir. Usá letras grandes y suficientes lápices. Si dos personas completan juntas, aceptá el empate para mantener el ritmo sin discutir por un premio pequeño.'),
   section('2. Adivinar la panza', 'Esta propuesta solo tiene sentido si la homenajeada se siente cómoda. Preguntale antes, en privado, y evitá comentarios sobre su cuerpo. Una variante más tranquila consiste en adivinar la circunferencia de un globo decorativo con una cinta. Cada participante corta su estimación y luego comparan. No uses cintas sobre una persona sin permiso. Si la idea no entusiasma, reemplazala por adivinar cuántos botones hay en un frasco cerrado.'),
   section('3. No digas bebé', 'Al empezar una ronda, entregá una ficha de papel a cada participante. Durante diez minutos, quien diga la palabra elegida entrega su ficha a quien lo nota. Explicá que solo cuenta dentro de esa ronda; nadie tiene que estar pendiente toda la tarde. Ganará quien reúna más fichas. No sujetes broches a la ropa de otras personas. Podés elegir otra palabra si hay invitados que no quieren jugar con esa regla.'),
   section('4. El chupete escondido', 'Escondé dibujos de chupetes en lugares visibles del área de juegos, sin mover pertenencias ni usar cocina o baño. Contá las tarjetas antes y después para saber si falta alguna. Por equipos, buscan durante unos minutos y vuelven con sus hallazgos. Para quienes prefieren quedarse sentados, prepará una lámina con dibujos mezclados y pediles encontrar los chupetes. Evitá objetos pequeños sueltos si hay niños; las tarjetas grandes alcanzan para la actividad.'),
   section('5. Carrera de pañales', 'Usá muñecos, pañales limpios y una mesa estable. Cada equipo elige a una persona para poner el pañal mientras otra lee los pasos. No hace falta correr ni vendar los ojos: el desafío puede ser coordinarse sin apuro. Comparen cómo quedó antes de contar el tiempo. Si faltan muñecos, hacé turnos con el mismo material. Nunca uses un bebé real para competir ni presentes el juego como una prueba de quién cuidará mejor.'),
   section('6. ¿Quién es ese bebé?', 'Pedí con anticipación una foto de infancia a quienes quieran participar y asignale un número. Mostralas en una cartulina o desde un teléfono, sin publicar las imágenes. Cada equipo anota a quién cree reconocer. Al revelar las respuestas, dejá que cada persona cuente una anécdota si quiere. Acordá después qué hacer con las copias. Si solo llegaron pocas fotos, usá esta actividad como charla grupal y no como competencia por puntos.'),
   section('7. La bolsa misteriosa', 'Poné objetos grandes y conocidos dentro de una bolsa de tela: una manta doblada, un babero o un cepillo. Quien participa intenta reconocer uno tocándolo desde afuera o metiendo la mano, según lo acordado. No incluyas alimentos, elementos cortantes ni cosas personales delicadas. Permití pasar el turno. Prepará una lista de respuestas para que quien dirige no improvise. Con pocos objetos, la gracia está en describir la sensación antes de decir el nombre.'),
   section('8. Palabras desordenadas', 'Escribí palabras vinculadas al bebé con sus letras mezcladas y dejá espacio para la respuesta. Probá resolverlas antes para detectar errores. Combiná palabras cortas y largas; una hoja demasiado difícil puede frenar la conversación. Armá parejas para que nadie quede expuesto por su velocidad de lectura. Al terminar, leé las soluciones en voz alta. Podés adaptar el tamaño de letra y eliminar el límite de tiempo si el grupo lo disfruta más así.'),
   section('9. Mensajes para el futuro', 'Repartí tarjetas con una frase inicial: deseo que, me gustaría enseñarte o una historia de tu familia. Cada invitado completa lo que quiera y firma si le parece. Guardá los mensajes en un sobre para leerlos más adelante. Esta actividad no necesita ganador. Evitá pedir consejos íntimos o experiencias difíciles frente al grupo. Si alguien prefiere dibujar, dejá que lo haga. Una caja simple alcanza; no hace falta comprar un recuerdo para cada tarjeta.'),
   section('10. Memoria de la bandeja', 'Mostrá una bandeja con varios objetos durante un minuto y después tapala. Los equipos anotan lo que recuerdan. Elegí elementos distintos para que la dificultad venga de la memoria y no de distinguir piezas casi iguales. Leé el inventario al final y aceptá nombres equivalentes. Prepará la bandeja antes de que lleguen los invitados. Para cerrar, dejá unos minutos libres de juego y volvé a la merienda: no es necesario completar toda la lista.')
  ]
 },
 {
  slug: 'baby-shower-sencillo-en-casa', title: 'Baby shower sencillo en casa: guía y compras',
  h1: 'Baby shower sencillo en casa: cómo armarlo y qué comprar',
  description: 'Prepará un baby shower sencillo en casa con una lista de compras razonable, decoración simple y tareas repartidas. Elegí qué hacer y qué consultar.',
  datePublished: '2026-09-19', theme: 'mariposas', offer: nube,
  cta: 'Si preferís que llegue listo', image: 'Composición ilustrativa de un rincón de casa con figuras de papel y una mesa sencilla',
  intro: 'Hacer el baby shower en casa permite aprovechar lo que ya tenés y elegir un ritmo tranquilo. También implica ocuparse de sillas, comida, limpieza y recepción. La clave no es decorar cada ambiente, sino preparar un rincón cómodo y repartir el trabajo. Antes de comprar, mirá la casa con una lista en la mano y decidí qué podés resolver vos, qué te pueden prestar y qué preferís consultar.',
  sections: [
   section('Elegí el espacio y una lista de invitados posible',
    'Medí la pared donde querés sacar fotos y el espacio que queda delante de la mesa. Abrí puertas y mové las sillas como se usarían durante la reunión. Si para pasar al baño hay que atravesar la decoración, cambiá la distribución antes de armarla. En un departamento, consultá las reglas del edificio y avisá cómo será el ingreso. En una casa con patio, prepará una alternativa bajo techo desde el principio.',
    'Ajustá la lista de invitados a los asientos y al espacio real. Pensá dónde van a quedar bolsos, regalos y cochecitos. Un encuentro chico no necesita varias mesas temáticas. Podés disponer la comida en un lado y las bebidas en otro para repartir el movimiento. Elegí un horario que te permita preparar con calma, y explicá en la invitación si será una merienda o una comida para que nadie llegue con otra expectativa.'),
   section('Decoración sencilla con lo que ya tenés',
    'Elegí dos colores y un motivo fácil de repetir. Para mariposas, recortá figuras de papel grueso de distintos tamaños y probá su ubicación sobre la mesa antes de fijarlas. Un mantel liso, un cartel y unas pocas figuras pueden resolver el fondo. Revisá que el material de fijación sea adecuado para tu pared. No improvises soportes pesados ni te subas a muebles inestables para colgar adornos.',
    'Separá primero las fuentes, frascos y bandejas que ya existen en casa. Usá alturas moderadas y bases firmes; una mesa linda también tiene que permitir servir sin volcar cosas. Dejá espacio libre delante de cada plato. Si comprás globos, pensá quién los va a preparar y dónde quedarán los restos. No hace falta aprender un arco complejo la noche anterior: un conjunto pequeño bien ubicado puede acompañar el cartel sin taparlo.'),
   section('Qué comprar y qué pedir prestado',
    'Dividí tu lista en comida, servicio, decoración y limpieza. En servicio anotá vasos, platos, cubiertos, servilletas, jarras y recipientes. Contá lo que tenés antes de sumar paquetes al carrito. Si pedís sillas prestadas, confirmá cantidad, retiro y devolución. También revisá las mesas: tener suficientes asientos no sirve si no hay dónde apoyar una bebida. Marcá cada objeto prestado para que después vuelva a su dueño.',
    'Para decoración, comprá solo lo que corresponde al rincón elegido. Evitá llevar recuerdos, centros de mesa y carteles extra por impulso. Guardá cinta, tijera y materiales juntos, fuera del alcance de los niños. Incluí bolsas de residuos, paños y recipientes para guardar lo que sobre. Esas compras se ven menos, pero simplifican el cierre. Anotá un responsable al lado de cada tarea; escribir familia no alcanza para saber quién la va a hacer.'),
   section('Merienda, bebidas y dos juegos',
    'Podés combinar chipitas, sándwiches pequeños y algo dulce, según el horario y las preferencias del grupo. Si varias personas aportan comida, armá una lista compartida con cantidades y momento de llegada. Preguntá por necesidades alimentarias y confirmá las opciones con quien prepara cada cosa. Dejá bebidas y vasos en un lugar accesible. Contá también agua, hielo y espacio para conservar lo que lo necesite según las indicaciones de preparación.',
    'Elegí dos juegos que no exijan mover todos los muebles. Un bingo o tarjetas con mensajes se pueden hacer sentados y con pocos materiales. Prepará las hojas y lápices antes del día del encuentro. Una persona puede explicar las reglas mientras otra reparte. No armes un programa tan ajustado que haya que cortar una conversación para cumplirlo. Si los invitados están cómodos charlando, dejá que la merienda siga su curso.'),
   section('Qué podés delegar y cómo ordenar el presupuesto',
    `Hacerlo vos tiene un costo de materiales y también de tiempo. Compará ambos antes de decidir. ${nube.name}: ${priceCaption(nube.price)} La propuesta contempla decoración, con montaje y desmontaje incluidos en la estimación. La comida, las mesas y las sillas requieren una organización aparte. Si buscás sumar torta, ${torta.name}: ${priceCaption(torta.price)} Confirmá alcance y disponibilidad antes de incorporarla a tu lista.`,
    'El día anterior, dejá listo lo que no dependa de la comida: cartel, distribución, vajilla y materiales de juegos. El día del evento, asigná a alguien la puerta y a otra persona la reposición de bebidas. Después, separá objetos prestados y residuos antes de desarmar todo junto. Consultar una parte del trabajo no te obliga a delegar el festejo completo; elegí el apoyo que te deje disfrutar con menos pendientes.')
  ]
 },
 {
  slug: 'revelacion-de-genero-sencilla', title: 'Revelación de género sencilla: 7 ideas en casa',
  h1: 'Revelación de género sencilla: 7 ideas para hacerla en casa',
  description: 'Compará siete ideas para una revelación sencilla en casa. Organizá el secreto, el lugar y la limpieza, y consultá el Kit Sorpresa con precio estimado.',
  datePublished: '2026-09-19', theme: 'nubes-y-ositos', offer: kit,
  cta: 'Consultá una propuesta sencilla para compartir la sorpresa', image: 'Composición ilustrativa de un globo oscuro y una caja sobre un fondo celeste suave',
  intro: 'Una revelación puede ser un momento breve dentro de una merienda, sin escenario grande ni muchos accesorios. Elegí una sola sorpresa y acordá quién guarda el secreto. Una persona de tu confianza nos pasa solo el color por WhatsApp. No nos envíes estudios médicos. Antes de elegir el efecto, revisá dónde se hará, quiénes estarán cerca y quién va a juntar los materiales al terminar. La emoción no depende del ruido ni del tamaño.',
  sections: [
   section('1. Globo con confeti', 'Un globo oscuro permite ocultar el color hasta el momento elegido. Definí quién lo prepara, cómo se entrega y dónde esperará sin que alguien lo toque por curiosidad. Consultá las instrucciones del producto antes de usarlo y despejá el sector. Si el ruido incomoda a alguien, avisá previamente y ofrecé mirar desde otra habitación. Juntá enseguida los restos y el confeti, especialmente si hay niños o mascotas. No es necesario cubrir todo el piso para lograr una foto del momento.'),
   section('2. Humo de color, solo en exterior', 'El humo requiere un espacio exterior adecuado y condiciones que deben confirmarse con quien lo provee. No lo uses dentro de la casa, en un quincho cerrado ni como sustituto de un globo para una sala. Revisá las instrucciones y las restricciones del lugar antes de considerarlo. Si no podés confirmar esas condiciones, elegí otra idea. El humo de color y el polvo holi son adicionales a confirmar, sin un precio publicado ni inclusión automática en un kit. No improvises mezclas ni dispositivos caseros.'),
   section('3. Torta con el color adentro', 'Una torta permite hacer la revelación al servir la merienda, sin sumar una actividad separada. La persona que conoce el color puede acordar el relleno con quien la prepara y coordinar una entrega discreta. Confirmá porciones, sabores, necesidades alimentarias y conservación. Prepará plato, cuchillo y una superficie estable antes de reunir a la familia. Si alguien quiere filmar, ubicá el teléfono de antemano para no demorar el corte. La cobertura exterior puede acompañar una temática neutra y mantener la sorpresa hasta la primera porción.'),
   section('4. Piñata con cintas', 'Una piñata que se abre tirando de cintas puede evitar golpes y permitir que varias personas participen. Consultá cómo funciona el modelo y probalo sin el contenido final si el diseño lo permite. Sujetala únicamente en un punto adecuado, sin improvisar con lámparas o muebles. Dejá suficiente espacio alrededor y organizá turnos. Elegí piezas de papel fáciles de recoger y evitá mezclar objetos duros. Si el ambiente es chico, reemplazá la piñata por un sobre grande que se abra sobre una mesa.'),
   section('5. Caja de globos', 'Decorá una caja opaca y colocá adentro globos del color elegido. No necesitás soltarlos al aire libre: podés fijarlos con cintas para que permanezcan junto a la caja al abrirla. Revisá que la tapa abra fácilmente y no revele el contenido antes de tiempo. Elegí el tamaño según el espacio donde la vas a guardar. Una persona puede traerla al momento de la sorpresa, mientras otra despeja la mesa. Después, guardá las cintas y los restos antes de que vuelvan a circular niños o mascotas.'),
   section('6. Confeti popper', 'Si elegís un lanzador comercial de confeti, leé las instrucciones del fabricante y confirmá que sea apropiado para el lugar. Nunca lo apuntes hacia personas, animales, comida o elementos frágiles. Acordá quién lo maneja y evitá que varios invitados lo accionen sin coordinación. No hagas versiones caseras con presión o materiales improvisados. Para una reunión tranquila, una alternativa es abrir sobres con papel de color. Prepará bolsas y una escoba antes de empezar; la limpieza también forma parte del plan, sobre todo en patios compartidos.'),
   section('7. Camiseta con mensaje', 'Una camiseta doblada dentro de una bolsa puede revelar el color o un mensaje cuando la abren. Es una opción sin estallidos y fácil de adaptar a una videollamada. Confirmá el diseño y la escritura antes de mandarla a preparar. No hace falta que todos compren ropa especial; alcanza una pieza que luego quieran guardar. Pensá cómo mostrarla a quienes están lejos y pedí permiso antes de compartir fotos de los invitados. Si el color no se distingue bien en cámara, agregá una tarjeta con el mensaje.'),
   section('Cómo coordinar el secreto y la reunión', 'Elegí una persona responsable del color y otra de recibir a los invitados, así no recae todo en quien guarda la sorpresa. Revisá que las bolsas o mensajes no muestren el dato antes de tiempo. Mandá una invitación con horario y dirección, prepará asientos y una merienda sencilla, y definí qué harán si llueve. Si querés consultar un kit, enviá fecha tentativa, zona y la idea elegida. El precio final y la disponibilidad se revisan por WhatsApp; una consulta no confirma el evento. Cerrá el encuentro con tiempo para conversar, sin encadenar varias revelaciones ni repetir efectos para conseguir otra toma.')
  ]
 },
 {
  slug: 'que-se-necesita-para-un-baby-shower', title: 'Qué se necesita para un baby shower: checklist',
  h1: 'Qué se necesita para un baby shower: checklist completa',
  description: 'Ordená tu baby shower por categorías y semanas: invitados, espacio, comida, decoración y tareas del día. Usá esta lista para preparar tu consulta.',
  datePublished: '2026-09-19', theme: 'safari', offer: estrella,
  cta: 'Consultá el alcance para tu lista de invitados', image: 'Composición ilustrativa de una lista, un lápiz y tarjetas sobre una mesa en tonos crema',
  intro: 'Una lista útil no reúne todo lo que podrías comprar: separa lo necesario de lo opcional y le asigna una persona a cada tarea. Para un baby shower necesitás definir invitados, lugar, comida y una forma de recibir a la familia. La decoración y los juegos acompañan esa base. Usá esta checklist como una hoja de trabajo: anotá responsable, fecha y estado junto a cada punto, y ajustala al tamaño de tu reunión.',
  sections: [
   section('Invitados, fecha y comunicación',
    'Anotá nombres y cantidad de acompañantes, distinguiendo adultos y niños. Sumá un espacio para confirmar asistencia y otro para observaciones prácticas, como necesidad de acceso sin escalones. Definí quién enviará las invitaciones y responderá dudas. Incluí dirección, referencia de llegada, horario y un teléfono de contacto. No necesitás una invitación impresa; un mensaje claro permite actualizar información sin volver a comprar materiales.',
    'Acordá con la familia qué tipo de encuentro quiere la homenajeada. Algunas personas disfrutan los juegos y otras prefieren conversar. Consultá antes de organizar una sorpresa o pedir fotos para mostrar en público. Elegí una fecha tentativa y una alternativa si todavía dependés del lugar. Evitá anunciar servicios o una disponibilidad que no estén confirmados. La lista de invitados puede empezar aproximada, pero alguien tiene que actualizarla cuando lleguen respuestas.'),
   section('Lugar, muebles y acceso',
    'Revisá asientos, mesas, baño, ventilación y un sector para apoyar regalos. Medí el lugar de la decoración y dejá circulación alrededor. Si hay patio, escribí cuál será la alternativa bajo techo. En un salón o edificio, consultá ingreso de materiales, reglas de paredes, horarios y retiro. Indicá escaleras o ascensores al pedir una propuesta; una foto del rincón no muestra todo el recorrido desde la entrada.',
    'Separá lo propio, lo prestado y lo que necesitás conseguir. Confirmá mesas, sillas, mantelería, vajilla y limpieza posterior, porque no son detalles que aparezcan solos al elegir decoración. Nombrá a quien recibe cada entrega y a quien devuelve objetos prestados. Dejá libre el acceso principal y evitá cables sueltos por las zonas de paso. La distribución debe funcionar cuando la gente esté sentada y cuando se levante a servirse.'),
   section('Comida, bebidas y elementos para servir',
    'Elegí el menú según el horario: merienda y almuerzo no requieren lo mismo. Contá unidades por preparación y compará esa lista con los invitados confirmados. Si habrá chipitas, empanaditas, dulces y torta, registrá quién aporta cada cosa. Preguntá por necesidades alimentarias y verificá qué opciones pueden ofrecer quienes preparan la comida. No prometas una adaptación sin haber conversado sus condiciones.',
    'Sumá agua, otras bebidas, hielo, vasos, servilletas, cubiertos y utensilios para servir. Confirmá el espacio y las indicaciones para conservar cada preparación. Asigná a alguien la reposición de bandejas y bebidas, y prepará recipientes para guardar lo que sobre. Una mesa decorada no reemplaza esta organización. Si varias personas llevan comida, acordá cantidades y llegada para no recibir todos los salados cuando ya terminó la merienda.'),
   section('Decoración, juegos y presupuesto',
    `Elegí temática, colores y un rincón principal para fotos. Registrá cartel, fondo y elementos de mesa, distinguiendo lo imprescindible de lo opcional. Para comparar una propuesta, ${estrella.name}: ${priceCaption(estrella.price)} Revisá cantidades, invitados incluidos y exclusiones antes de sumar adicionales. Los importes orientan la consulta; el alcance debe quedar claro por escrito. No cuentes torta o souvenirs como incluidos en cualquier combo.`,
    'Para juegos, elegí dos actividades, prepará materiales y nombrá a quien explica las reglas. Para fotos, decidí quién se ocupa y pedí permiso antes de publicar imágenes de otras personas. Armá el presupuesto por categorías, incluyendo traslado cuando corresponda. Marcá los objetos que ya tenés para no comprarlos otra vez. Conservá una lista única actualizada: varias listas en distintos chats hacen fácil duplicar encargos y olvidar tareas.'),
   section('Cronograma: seis semanas antes al día del evento',
    'Seis semanas antes, conversá sobre el tipo de reunión, definí invitados aproximados y mirá opciones de lugar. Cuatro semanas antes, elegí temática y repartí tareas. Unas tres semanas antes, consultá decoración y comida con fecha, zona y cantidad de personas. Estos plazos sirven para organizarte, no garantizan disponibilidad. Si tenés menos tiempo, simplificá la propuesta y priorizá espacio, asientos y merienda.',
    'Dos semanas antes, enviá o recordá las invitaciones y revisá respuestas. Una semana antes, actualizá cantidades, entregas y responsables. El día anterior, prepará vajilla, juegos y distribución sin bloquear los accesos. El día del evento, repasá baño, bebidas, recepción y limpieza con quienes ayudan. Al terminar, devolvé lo prestado y guardá recuerdos. Dejá margen para descansar y conversar: completar la checklist tiene sentido si te permite disfrutar del encuentro, no si te mantiene trabajando toda la tarde.')
  ]
 }
];
